name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.12' ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment-dev.yml
        environment-name: jupytergis
        create-args: python=${{ matrix.python-version }}

    - name: Install test packages
      run: pip install pytest pytest-qgis dirty-equals

    - name: Run tests
      run: QT_QPA_PLATFORM=offscreen pytest --color=yes -v python/jupytergis_core/tests
